export const LANGUAGES = [
    { value: "german", label: "German" },
    { value: "english", label: "English" },
    { value: "french", label: "French" },
    { value: "spanish", label: "Spanish" },
    { value: "italian", label: "Italian" },
    { value: "portuguese", label: "Portuguese" },
    { value: "russian", label: "Russian" },
    { value: "chinese", label: "Chinese" },
    { value: "japanese", label: "Japanese" },
    { value: "korean", label: "Korean" },
    { value: "arabic", label: "Arabic" },
    { value: "turkish", label: "Turkish" },
    { value: "polish", label: "Polish" },
    { value: "dutch", label: "Dutch" },
    { value: "hungarian", label: "Hungarian" },
    { value: "finnish", label: "Finnish" },
    { value: "swedish", label: "Swedish" },
    { value: "norwegian", label: "Norwegian" },
    { value: "danish", label: "Danish" },
    { value: "greek", label: "Greek" },
    { value: "indonesian", label: "Indonesian" },
    { value: "thai", label: "Thai" },
    { value: "malay", label: "Malay" },
    { value: "filipino", label: "Filipino" },
    { value: "lao", label: "Lao" },
    { value: "tibetan", label: "Tibetan" },
    { value: "khmer", label: "Khmer" },
    { value: "vietnamese", label: "Vietnamese" },
    { value: "orcish", label: "Orcish" },
    { value: "sanskrit", label: "Sanskrit" },
    { value: "bengali", label: "Bengali" },
    { value: "tamil", label: "Tamil" },
    { value: "telugu", label: "Telugu" },
    { value: "gujarati", label: "Gujarati" },
    { value: "kannada", label: "Kannada" },
    { value: "malayalam", label: "Malayalam" },
    { value: "marathi", label: "Marathi" },
    { value: "oriya", label: "Oriya" },
    { value: "punjabi", label: "Punjabi" },
    { value: "sinhala", label: "Sinhala" },
    { value: "urdu", label: "Urdu" },
    { value: "yiddish", label: "Yiddish" },
    { value: "hebrew", label: "Hebrew" },
];

export const SYSTEM_MODES = [
    {
        value: "system",
        label: "System",
    },
    {
        value: "dark",
        label: "Dark",
    },
    {
        value: "light",
        label: "Light",
    },
];
